spring:
  application:
    name: auth-client
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oauth_client?characterEncoding=UTF-8&useSSL=false
    username: oauth_client
    password: oauth_client
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 9
server:
  port: 9000
  servlet:
    context-path: /client-user
#    session:
#      cookie:
#        name: CLIENTSESSION

security:
  oauth2:
    client:
      client-id: user-client
      client-secret: user-secret-8888
      user-authorization-uri: http://localhost:8080/oauth/authorize
      access-token-uri: http://localhost:8080/oauth/token
    resource:
      jwt:
        key-uri: http://localhost:8080/oauth/token_key
        key-value: dev  # server端下发
    authorization:
      check-token-access: http://localhost:8080/oauth/check_token