spring:
  application:
    name: shardingsphere
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        initial-size: 5  #druid config 初始化大小，最小，最大
        min-idle: 5
        max-active: 20
        max-wait: 60000    # 配置获取连接等待超时的时间
        time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        min-evictable-idle-time-millis: 300000  # 配置一个连接在池中最小生存的时间，单位是毫秒
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true # 打开PSCache，并且指定每个连接上PSCache的大小
        max-pool-prepared-statement-per-connection-size: 20
        filter:   # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
           commons-log:
             connection-logger-name: stat,wall,log4j
           stat:
             log-slow-sql: true
             slow-sql-millis: 2000
        connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        use-global-data-source-stat: true  # 合并多个DruidDataSource的监控数据
        stat-view-servlet:
           enabled: true       #StatViewServlet配置展示Druid的统计信息,StatViewServlet的用途包括：1.提供监控信息展示的html页面2.提供监控信息的JSON API 是否启用StatViewServlet默认值true
           url-pattern: /druid/*   #根据配置中的url-pattern来访问内置监控页面，如果是上面的配置，内置监控页面的首页是/druid/index.html例如：http://ip:port/druid/index.html
           reset-enable: true      #允许清空统计数据
           login-username: admin
           login-password: admin

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kwq.root.shardingsphere.model

# 分页配置
pagehelper:
  helper-dialect: mysql
  #为了使用输入页数为负或者超出最大页时候使页数为最小或最大值
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#xss攻击拦截，excludes为不拦截的请求，使用“,”分隔
xss:
  excludes:
    /swagger-resources/**,
    /swagger-ui.html,
    /v2/**,
    /webjars/**,
    /csrf
